---
# Install tmux
- name: Copy .tmux.conf
  copy: src=tmux.conf dest="{{ home }}/.tmux.conf"

- name: Install tmux using apt
  apt: name={{ item }} state=present update_cache=yes force=yes
  sudo: yes
  with_items:
    - tmux
