---

- name: Install node.js and other tools for developing node.js apps
  hosts: nodejs
  vars:
    home: "/home/vagrant"
    node_version: 0.12.4

  tasks:

    - name: Import the public key used by the package management system.
      shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
      sudo: true


    - name: Create a list file for MongoDB.
      shell: echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
      sudo: true

    - name: Create a list file for Redis.
      shell: echo "deb http://ppa.launchpad.net/chris-lea/redis-server/ubuntu "$(lsb_release -sc)" main" | sudo tee /etc/apt/sources.list.d/redis-server3.list
      sudo: true

    - name: Update Redis list file.
      shell: echo "deb http://ppa.launchpad.net/chris-lea/redis-server/ubuntu "$(lsb_release -sc)" main" | sudo tee -a /etc/apt/sources.list.d/redis-server3.list
      sudo: true

    - name: Install tools using apt
      apt: name={{ item }} state=present update_cache=yes force=yes
      sudo: yes
      with_items:
        - make 
        - curl 
        - build-essential 
        - libssl-dev 
        - tree
        - mongodb-org
        - git-core
        - tmux
        - redis-server

