---
# Install nodejs

- name: Restart machine
  command: reboot "Ansible updates triggered"
  sudo: true
  async: 0
  poll: 0
  ignore_errors: true

- name: Waiting for machine to come back
  local_action: wait_for host=nodejs state=started
  sudo: false        

- name: Copy .profile
  copy: src=profile dest="{{ home }}/.profile"

- name: "Install node.js {{ node_version }}"
  shell: ". {{ home }}/.profile && nvm install {{ node_version }}"
  sudo: false        
  

- name: "Set nvm alias default {{ node_version }}"
  shell: ". {{ home }}/.profile && nvm alias default {{ node_version }}"
  sudo: false
