---
# Install nvm
- name: Install tools using apt
  apt: name={{ item }} state=present update_cache=yes
  sudo: yes
  with_items:
    - curl 
    - build-essential 
    - libssl-dev 

- name: Install nvm 
  shell: "curl https://raw.githubusercontent.com/creationix/nvm/v0.16.1/install.sh | sh"

