syntax on
filetype plugin indent on
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab
set number
set list
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
set mouse=""
set noswapfile
set nobackup
