---
# Install mongodb
- name: Import the public key used by the package management system.
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  sudo: true


- name: Create a list file for MongoDB.
  shell: echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
  sudo: true

- name: Install MongoDB using apt
  apt: name={{ item }} state=present update_cache=yes force=yes
  sudo: yes
  with_items:
    - mongodb-org

